Consumable[] =
{
/*	{Loot_MAGAZINE,		8,		ItemBandage},
	{Loot_MAGAZINE,		4,		ItemHeatPack},
	{Loot_MAGAZINE,		3,		ItemPainkiller},
	{Loot_MAGAZINE,		3,		ItemAntibacterialWipe},*/
	
	{Loot_MAGAZINE,		3,		ItemWaterBottleUnfilled}, //TODO: replace with canteen to better fit Epoch lootPosSmall
	{Loot_MAGAZINE,		3,		ItemWaterBottleSafe},
	{Loot_MAGAZINE,		3,		ItemWaterBottle},
	{Loot_MAGAZINE,		3,		ItemHeatPack},
	
	{Loot_MAGAZINE,		3,		ItemSodaCoke},
	{Loot_MAGAZINE,		3,		ItemSodaPepsi},
	{Loot_MAGAZINE,		1,		ItemSodaMdew},
	{Loot_MAGAZINE,		1,		ItemSodaRbull},
	{Loot_MAGAZINE,		1,		ItemSodaOrangeSherbet},

	{Loot_MAGAZINE,		2,		ItemSodaMtngreen},
	{Loot_MAGAZINE,		5,		ItemSodaR4z0r},
	{Loot_MAGAZINE,		5,		ItemSodaClays},
	{Loot_MAGAZINE,		5,		ItemSodaSmasht},
	{Loot_MAGAZINE,		5,		ItemSodaDrwaste},
	{Loot_MAGAZINE,		5,		ItemSodaFranka},
	{Loot_MAGAZINE,		5,		ItemSodaLemonade},
	{Loot_MAGAZINE,		5,		ItemSodaLirik},
	{Loot_MAGAZINE,		2,		ItemSodaLvg},
	{Loot_MAGAZINE,		5,		ItemSodaMzly},
	{Loot_MAGAZINE,		5,		ItemSodaPeppsy},
	{Loot_MAGAZINE,		2,		ItemSodaRabbit},
	{Loot_MAGAZINE,		5,		ItemSodaSacrite},
	{Loot_MAGAZINE,		1,		ItemSodaRocketFuel},
	{Loot_MAGAZINE,		1,		ItemSodaGrapeDrink},
	{Loot_MAGAZINE,		1,		ItemSherbet},
	
	{Loot_MAGAZINE,		3,		FoodPistachio},
	{Loot_MAGAZINE,		4,		FoodNutmix},
	{Loot_MAGAZINE,		4,		FoodChipsSulahoops},
	{Loot_MAGAZINE,		4,		FoodChipsMysticales},
	{Loot_MAGAZINE,		4,		FoodChipsChocolate},
	{Loot_MAGAZINE,		4,		FoodCandyChubby},
	{Loot_MAGAZINE,		4,		FoodCandyAnders},
	{Loot_MAGAZINE,		4,		FoodCandyLegacys},
	{Loot_MAGAZINE,		4,		FoodCandyMintception},
	{Loot_MAGAZINE,		4,		FoodCakeCremeCakeClean},
	
	{Loot_MAGAZINE,		5,		FoodCanBeef},
	{Loot_MAGAZINE,		5,		FoodCanPotatoes},
	{Loot_MAGAZINE,		5,		FoodCanGriff},
	{Loot_MAGAZINE,		5,		FoodCanBadguy},
	{Loot_MAGAZINE,		5,		FoodCanBoneboy},
	{Loot_MAGAZINE,		5,		FoodCanCorn},
	{Loot_MAGAZINE,		5,		FoodCanCurgon},
	{Loot_MAGAZINE,		5,		FoodCanDemon},
	{Loot_MAGAZINE,		5,		FoodCanFraggleos},
	{Loot_MAGAZINE,		5,		FoodCanHerpy},
	{Loot_MAGAZINE,		5,		FoodCanDerpy},
	{Loot_MAGAZINE,		5,		FoodCanOrlok},
	{Loot_MAGAZINE,		5,		FoodCanPowell},
	{Loot_MAGAZINE,		5,		FoodCanTylers},
	
	{Loot_MAGAZINE,		4,		FoodCanUnlabeled},
	{Loot_MAGAZINE,		2,		FoodCanBakedBeans},
	{Loot_MAGAZINE,		2,		FoodCanSardines},
	{Loot_MAGAZINE,		2,		FoodCanFrankBeans},
	{Loot_MAGAZINE,		2,		FoodCanPasta},
	{Loot_MAGAZINE,		2,		FoodBioMeat},
	
	{Loot_MAGAZINE,		5,		FoodCanRusUnlabeled},
	{Loot_MAGAZINE,		5,		FoodCanRusStew},
	{Loot_MAGAZINE,		5,		FoodCanRusPork},
	{Loot_MAGAZINE,		5,		FoodCanRusPeas},
	{Loot_MAGAZINE,		4,		FoodCanRusMilk},
	{Loot_MAGAZINE,		5,		FoodCanRusCorn}
};