//Packaged Food
class Category_27 {
	class FoodCanBakedBeans {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanFrankBeans {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanPasta {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanSardines {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanBeef {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanPotatoes {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanGriff {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanBadguy {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanBoneboy {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanCorn {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanCurgon {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanDemon {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanFraggleos {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanHerpy {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanDerpy {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanOrlok {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanPowell {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanTylers {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanUnlabeled {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanRusUnlabeled {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanRusStew {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanRusPork {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanRusPeas {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanRusMilk {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCanRusCorn {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodChipsSulahoops {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodChipsMysticales {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodChipsChocolate {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCandyChubby {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCandyAnders {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCandyLegacys {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCakeCremeCakeClean {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodCandyMintception {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodPistachio {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodNutmix {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class FoodMRE {type = "trade_items";buy[] = {-1,"ItemSilverBar10oz"};sell[] = {5,"ItemSilverBar"};};
};

//Cooked Meats
class Category_28 {
	class FoodbaconCooked {type = "trade_items";buy[] = {4,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class FoodbeefCooked {type = "trade_items";buy[] = {4,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class FoodchickenCooked {type = "trade_items";buy[] = {4,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class FoodGoatCooked {type = "trade_items";buy[] = {4,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class FoodmuttonCooked {type = "trade_items";buy[] = {4,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class FoodrabbitCooked {type = "trade_items";buy[] = {2,"ItemSilverBar10oz"};sell[] = {1,"ItemSilverBar10oz"};};
	// most common
	class FishCookedTrout {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemSilverBar10oz"};};
	// less common
	class FishCookedSeaBass {type = "trade_items";buy[] = {3,"ItemGoldBar"};sell[] = {2,"ItemSilverBar10oz"};};
	// rarest
	class FishCookedTuna {type = "trade_items";buy[] = {4,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
};

//Drinks
class Category_29 {
	class ItemWaterbottleUnfilled {type = "trade_items";buy[] = {3,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class ItemPlasticWaterbottleUnfilled {type = "trade_items";buy[] = {3,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};	
	class ItemSodaCoke {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class ItemSodaPepsi {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class ItemSodaMdew {type = "trade_items";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class ItemSodaMtngreen {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaR4z0r {type = "trade_items";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class ItemSodaClays {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaSmasht {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaDrwaste {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaFranka {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaLemonade {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaLirik {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaLvg {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaMzly {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaPeppsy {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaRabbit {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaSacrite {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaRocketFuel {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaGrapeDrink {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSherbet {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class ItemSodaRbull {type = "trade_items";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class ItemSodaOrangeSherbet {type = "trade_items";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class ItemWaterbottle {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class ItemWaterBottleInfected {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class ItemWaterBottleSafe {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class ItemWaterBottleBoiled {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {3,"ItemSilverBar"};};
	class ItemWaterBottleHerbal {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {5,"ItemSilverBar10oz"};};
	class ItemPlasticWaterbottle {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class ItemPlasticWaterBottleInfected {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class ItemPlasticWaterBottleSafe {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class ItemPlasticWaterBottleBoiled {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {3,"ItemSilverBar"};};
	class ItemPlasticWaterBottleHerbal {type = "trade_items";buy[] = {-3,"ItemSilverBar"};sell[] = {5,"ItemSilverBar10oz"};};	
};

//Clothes
class Category_30 {
	class Skin_SurvivorW2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_SurvivorW3_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_SurvivorWpink_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_SurvivorWurban_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_SurvivorWcombat_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_SurvivorWwinter_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_SurvivorWdesert_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_DoctorW_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_WorkerW_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_PolicemanW_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_PriestW_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_HookerW1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_HookerW2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_HookerW3_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_HookerW4_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_HookerW5_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};		
	class Skin_Functionary1_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Haris_Press_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Priest_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Survivor2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Rocker1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Rocker2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Rocker3_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Rocker4_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_RU_Policeman_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_RU_Policeman2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Pilot_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_INS_Lopotev_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Doctor_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Assistant_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Worker1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Worker3_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Worker4_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_TK_CIV_Takistani01_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_TK_CIV_Takistani03_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_TK_CIV_Takistani04_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_TK_CIV_Takistani06_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_Firefighter1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Firefighter2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Firefighter3_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Firefighter4_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Firefighter5_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Firefighter_Officer1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Firefighter_Officer2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_Postman1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Postman2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Postman3_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Postman4_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Hunter_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Gardener_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_SchoolTeacher_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian3_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian4_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian5_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian6_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian7_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian8_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian9_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian10_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian11_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian12_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian13_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Civilian14_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Prisoner1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Prisoner2_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Prisoner3_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Reporter_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_MafiaBoss_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Dealer_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_BusinessMan_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
};

//Backpacks
class Category_31 {
	/* New Backpacks */
	class GymBag_Camo_DZE1 {type = "trade_backpacks";buy[] = {8,"ItemSilverBar"};sell[] = {4,"ItemSilverBar"};};
	class GymBag_Green_DZE1 {type = "trade_backpacks";buy[] = {8,"ItemSilverBar"};sell[] = {4,"ItemSilverBar"};};
	class Patrol_Pack_DZE1 {type = "trade_backpacks";buy[] = {8,"ItemSilverBar"};sell[] = {4,"ItemSilverBar"};};
	class Czech_Vest_Pouch_DZE1 {type = "trade_backpacks";buy[] = {1,"ItemSilverBar10oz"};sell[] = {5,"ItemSilverBar"};};
	class Assault_Pack_DZE1 {type = "trade_backpacks";buy[] = {2,"ItemSilverBar10oz"};sell[] = {1,"ItemSilverBar10oz"};};
	class TerminalPack_DZE1 {type = "trade_backpacks";buy[] = {4,"ItemSilverBar10oz"};sell[] = {2,"ItemSilverBar10oz"};};
	class TinyPack_DZE1 {type = "trade_backpacks";buy[] = {6,"ItemSilverBar10oz"};sell[] = {3,"ItemSilverBar10oz"};};
	class ALICE_Pack_DZE1 {type = "trade_backpacks";buy[] = {8,"ItemSilverBar10oz"};sell[] = {4,"ItemSilverBar10oz"};};
	class TK_Assault_Pack_DZE1 {type = "trade_backpacks";buy[] = {1,"ItemGoldBar"};sell[] = {5,"ItemSilverBar10oz"};};
	class School_Bag_DZE1 {type = "trade_backpacks";buy[] = {1,"ItemGoldBar"};sell[] = {5,"ItemSilverBar10oz"};};
	class CompactPack_DZE1 {type = "trade_backpacks";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class British_ACU_DZE1 {type = "trade_backpacks";buy[] = {4,"ItemGoldBar"};sell[] = {2,"ItemGoldBar"};};	
	class GunBag_DZE1 {type = "trade_backpacks";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class PartyPack_DZE1 {type = "trade_backpacks";buy[] = {7,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class NightPack_DZE1 {type = "trade_backpacks";buy[] = {8,"ItemGoldBar"};sell[] = {4,"ItemGoldBar"};};
	class SurvivorPack_DZE1 {type = "trade_backpacks";buy[] = {1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};
	class AirwavesPack_DZE1 {type = "trade_backpacks";buy[] = {12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_Camping_DZE1 {type = "trade_backpacks";buy[] = {12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_OD_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_DES_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_3DES_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_WDL_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_MAR_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_DMAR_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_UCP_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_6DES_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_TAK_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_NVG_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_BLK_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_DPM_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_FIN_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_MTC_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_NOR_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_WIN_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_ATC_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_MTL_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};
	class CzechBackpack_FTN_DZE1 {type = "trade_backpacks";buy[] = {-12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};	
	class WandererBackpack_DZE1 {type = "trade_backpacks";buy[] = {-14,"ItemGoldBar"};sell[] = {7,"ItemGoldBar"};};
	class LegendBackpack_DZE1 {type = "trade_backpacks";buy[] = {-16,"ItemGoldBar"};sell[] = {8,"ItemGoldBar"};};
	class CoyoteBackpack_DZE1 {type = "trade_backpacks";buy[] = {-18,"ItemGoldBar"};sell[] = {9,"ItemGoldBar"};};
	class CoyoteBackpack_Camping_DZE1 {type = "trade_backpacks";buy[] = {-18,"ItemGoldBar"};sell[] = {9,"ItemGoldBar"};};
	class CoyoteBackpackDes_DZE1 {type = "trade_backpacks";buy[] = {-18,"ItemGoldBar"};sell[] = {9,"ItemGoldBar"};};
	class CoyoteBackpackWdl_DZE1 {type = "trade_backpacks";buy[] = {-18,"ItemGoldBar"};sell[] = {9,"ItemGoldBar"};};
	class LargeGunBag_DZE1 {type = "trade_backpacks";buy[] = {-2,"ItemGoldBar10oz"};sell[] = {1,"ItemGoldBar10oz"};};
	/* Old Backpacks - sell only */
	class DZ_Czech_Vest_Pouch {type = "trade_backpacks";buy[] = {-4,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class DZ_Patrol_Pack_EP1 {type = "trade_backpacks";buy[] = {-8,"ItemSilverBar"};sell[] = {4,"ItemSilverBar"};};		
	class DZ_Assault_Pack_EP1 {type = "trade_backpacks";buy[] = {-1,"ItemSilverBar10oz"};sell[] = {5,"ItemSilverBar"};};
	class DZ_TerminalPack_EP1 {type = "trade_backpacks";buy[] = {-2,"ItemSilverBar10oz"};sell[] = {1,"ItemSilverBar10oz"};};
	class DZ_ALICE_Pack_EP1 {type = "trade_backpacks";buy[] = {-6,"ItemSilverBar10oz"};sell[] = {3,"ItemSilverBar10oz"};};
	class DZ_TK_Assault_Pack_EP1 {type = "trade_backpacks";buy[] = {-8,"ItemSilverBar10oz"};sell[] = {4,"ItemSilverBar10oz"};};
	class DZ_CompactPack_EP1 {type = "trade_backpacks";buy[] = {-1,"ItemGoldBar"};sell[] = {5,"ItemSilverBar10oz"};};	
	class DZ_British_ACU {type = "trade_backpacks";buy[] = {-4,"ItemGoldBar"};sell[] = {2,"ItemGoldBar"};};
	class DZ_GunBag_EP1 {type = "trade_backpacks";buy[] = {-6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class DZ_CivilBackpack_EP1 {type = "trade_backpacks";buy[] = {-8,"ItemGoldBar"};sell[] = {4,"ItemGoldBar"};};
	class DZ_Backpack_EP1 {type = "trade_backpacks";buy[] = {-1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};
	class DZ_LargeGunBag_EP1 {type = "trade_backpacks";buy[] = {-1,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};	
};

//Miscellaneous
class Category_32 {
	class ItemKosmosSmokes {type = "trade_items";buy[] = {4,"ItemSilverBar10oz"};sell[] = {2,"ItemSilverBar10oz"};};
	class ItemKosmosSmokesOpen {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {1,"ItemSilverBar10oz"};};
	class ItemNewspaper {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class ItemBookBible {type = "trade_items";buy[] = {1,"ItemSilverBar10oz"};sell[] = {5,"ItemSilverBar"};};
	class ItemBook1 {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemSilverBar"};};
	class ItemBook2 {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemSilverBar"};};
	class ItemBook3 {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemSilverBar"};};
	class ItemBook4 {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemSilverBar"};};
	class ItemTrashPaperMusic {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class ItemTrashPaper {type = "trade_items";buy[] = {2,"ItemSilverBar"};sell[] = {1,"ItemSilverBar"};};
	class ItemLetter {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemSilverBar10oz"};};
	class ItemCards {type = "trade_items";buy[] = {4,"ItemSilverBar"};sell[] = {2,"ItemSilverBar"};};
	class ItemORP {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemARM {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemAVE {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemLRK {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemTNK {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemTruckORP {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemTruckARM {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemTruckAVE {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemTruckLRK {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemTruckTNK {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};		
	class ItemHeliAVE {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemHeliLRK {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemHeliTNK {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
	class ItemPlotDeed {type = "trade_items";buy[] = {-1,"ItemSilverBar"};sell[] = {5,"ItemGoldBar"};};
};