//Air Vehicles
class Category_1 {
	class pook_transport_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class pook_transport_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class pook_transport_CDF_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class pook_transport_CDF_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class pook_gunship_DZE {type = "trade_any_vehicle";buy[] = {4,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class pook_gunship_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class pook_gunship_CDF_DZE {type = "trade_any_vehicle";buy[] = {4,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class pook_gunship_CDF_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class AH6J_EP1_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class AH6J_EP1_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_CDF_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_CDF_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_WD_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_WD_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_2_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_2_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class UH1H_DES_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_DES_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_GREY_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_GREY_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_BLACK_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_BLACK_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class UH1H_SAR_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1H_SAR_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class Mi17_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_TK_EP1_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_TK_EP1_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_UN_CDF_EP1_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_UN_CDF_EP1_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_CDF_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_CDF_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_DES_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_DES_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_GREEN_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_GREEN_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_BLUE_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_BLUE_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_BLACK_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi17_BLACK_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Mi171Sh_CZ_EP1_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class Mi171Sh_CZ_EP1_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class MH60S_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class MH60S_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Ka60_GL_PMC_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class Ka60_GL_PMC_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class AW159_Lynx_BAF_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class AW159_Lynx_BAF_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class UH60M_EP1_DZE {type = "trade_any_vehicle";buy[] = {3,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH60M_EP1_DZ {type = "trade_any_vehicle";buy[] = {-3,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class UH1Y_DZE {type = "trade_any_vehicle";buy[] = {3,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class UH1Y_DZ {type = "trade_any_vehicle";buy[] = {-3,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class CH_47F_EP1_DZE {type = "trade_any_vehicle";buy[] = {4,"ItemBriefcase100oz"};sell[] = {2,"ItemBriefcase100oz"};};
	class CH_47F_EP1_DZ {type = "trade_any_vehicle";buy[] = {-4,"ItemBriefcase100oz"};sell[] = {2,"ItemBriefcase100oz"};};
	class CH_47F_EP1_Black_DZE {type = "trade_any_vehicle";buy[] = {4,"ItemBriefcase100oz"};sell[] = {2,"ItemBriefcase100oz"};};
	class CH_47F_EP1_Black_DZ {type = "trade_any_vehicle";buy[] = {-4,"ItemBriefcase100oz"};sell[] = {2,"ItemBriefcase100oz"};};
	class CH_47F_EP1_GREY_DZE {type = "trade_any_vehicle";buy[] = {4,"ItemBriefcase100oz"};sell[] = {2,"ItemBriefcase100oz"};};
	class CH_47F_EP1_GREY_DZ {type = "trade_any_vehicle";buy[] = {-4,"ItemBriefcase100oz"};sell[] = {2,"ItemBriefcase100oz"};};
	class CH_47F_EP1_DES_DZE {type = "trade_any_vehicle";buy[] = {4,"ItemBriefcase100oz"};sell[] = {2,"ItemBriefcase100oz"};};
	class CH_47F_EP1_DES_DZ {type = "trade_any_vehicle";buy[] = {-4,"ItemBriefcase100oz"};sell[] = {2,"ItemBriefcase100oz"};};	
};

//Ground Vehicles
class Category_2 {
	class Pickup_PK_TK_GUE_EP1_DZE {type = "trade_any_vehicle";buy[] = {8,"ItemGoldBar"};sell[] = {4,"ItemGoldBar"};};
	class Pickup_PK_TK_GUE_EP1_DZ {type = "trade_any_vehicle";buy[] = {-8,"ItemGoldBar"};sell[] = {4,"ItemGoldBar"};};
	class Pickup_PK_GUE_DZE {type = "trade_any_vehicle";buy[] = {1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};
	class Pickup_PK_GUE_DZ {type = "trade_any_vehicle";buy[] = {-1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};
	class Pickup_PK_INS_DZE {type = "trade_any_vehicle";buy[] = {1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};
	class Pickup_PK_INS_DZ {type = "trade_any_vehicle";buy[] = {-1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};
	class Offroad_DSHKM_Gue_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemGoldBar10oz"};sell[] = {1,"ItemGoldBar10oz"};};
	class Offroad_DSHKM_Gue_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemGoldBar10oz"};sell[] = {1,"ItemGoldBar10oz"};};
	class ArmoredSUV_PMC_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class ArmoredSUV_PMC_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class LandRover_MG_TK_EP1_DZE {type = "trade_any_vehicle";buy[] = {6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};	
	class LandRover_MG_TK_EP1_DZ {type = "trade_any_vehicle";buy[] = {-6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class LandRover_Special_CZ_EP1_DZE {type = "trade_any_vehicle";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class LandRover_Special_CZ_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class UAZ_MG_TK_EP1_DZE {type = "trade_any_vehicle";buy[] = {6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class UAZ_MG_TK_EP1_DZ {type = "trade_any_vehicle";buy[] = {-6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class BAF_Jackal2_L2A1_D_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class BAF_Jackal2_L2A1_D_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class BAF_Jackal2_L2A1_W_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class BAF_Jackal2_L2A1_W_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class BAF_Jackal2_GMG_D_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class BAF_Jackal2_GMG_D_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class BAF_Jackal2_GMG_W_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class BAF_Jackal2_GMG_W_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class BTR40_MG_TK_GUE_EP1_DZE {type = "trade_any_vehicle";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class BTR40_MG_TK_GUE_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class BTR40_MG_TK_INS_EP1_DZE {type = "trade_any_vehicle";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class BTR40_MG_TK_INS_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class GAZ_Vodnik_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class GAZ_Vodnik_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class BRDM2_HQ_TK_GUE_EP1_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class BRDM2_HQ_TK_GUE_EP1_DZ {type = "trade_any_vehicle";buy[] = {-2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};		
	class HMMWV_Armored_DZE {type = "trade_any_vehicle";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class HMMWV_Armored_DZ {type = "trade_any_vehicle";buy[] = {-1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class HMMWV_M2_DZE {type = "trade_any_vehicle";buy[] = {2,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class HMMWV_M2_DZ_DZ {type = "trade_any_vehicle";buy[] = {-12,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class HMMWV_M998A2_SOV_DES_EP1_DZE {type = "trade_any_vehicle";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class HMMWV_M998A2_SOV_DES_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class HMMWV_M1151_M2_CZ_DES_EP1_DZE {type = "trade_any_vehicle";buy[] = {4,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};
	class HMMWV_M1151_M2_CZ_DES_EP1_DZ {type = "trade_any_vehicle";buy[] = {-4,"ItemBriefcase100oz"};sell[] = {1,"ItemBriefcase100oz"};};	
	class T810A_PKT_ACR_DZE {type = "trade_any_vehicle";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class T810A_PKT_ACR_DZ {type = "trade_any_vehicle";buy[] = {-1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class T810A_PKT_DES_ACR_DZE {type = "trade_any_vehicle";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class T810A_PKT_DES_ACR_DZ {type = "trade_any_vehicle";buy[] = {-1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
};

//Weapons
class Category_3 {
	//Holo SD desert camo
	class G36C_Camo_Holo_SD_DZ {type = "trade_weapons";buy[] = {1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};
	class G36A_Camo_DZ {type = "trade_weapons";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class G36A_Camo_SD_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {7,"ItemGoldBar"};};
	class G36K_Camo_DZ {type = "trade_weapons";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class G36K_Camo_SD_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {7,"ItemGoldBar"};};	
	//CCO green camo
	class M4A1_Camo_CCO_DZ {type = "trade_weapons";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class M4A1_Camo_CCO_SD_DZ {type = "trade_weapons";buy[] = {1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};
	//GL Holo Green Camo
	class M4A1_Camo_Holo_GL_DZ {type = "trade_weapons";buy[] = {8,"ItemGoldBar"};sell[] = {4,"ItemGoldBar"};};
	class M4A1_Camo_Holo_GL_SD_DZ {type = "trade_weapons";buy[] = {12,"ItemGoldBar"};sell[] = {6,"ItemGoldBar"};};	
	//CCO FL Desert Camo
	class M4A3_DES_CCO_DZ {type = "trade_weapons";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	//ACOG GL Grey
	class M4A3_ACOG_GL_DZ {type = "trade_weapons";buy[] = {1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};	
	class FNFAL_ANPVS4_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {1,"ItemGoldBar10oz"};};
	// FN_FAL_ANPVS4_DZE has toggleable night vision
	class FN_FAL_ANPVS4_DZE {type = "trade_weapons";buy[] = {3,"ItemGoldBar10oz"};sell[] = {1,"ItemGoldBar10oz"};};
	class M240_DZ {type = "trade_weapons";buy[] = {2,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar"};};
	class M240_CCO_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {7,"ItemGoldBar"};};
	class M240_Holo_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {7,"ItemGoldBar"};};
	class Mk48_DZ {type = "trade_weapons";buy[] = {3,"ItemGoldBar10oz"};sell[] = {1,"ItemGoldBar10oz"};};
	class Mk48_CCO_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {12,"ItemGoldBar"};};
	class Mk48_Holo_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {12,"ItemGoldBar"};};
	class M249_m145_EP1_DZE {type = "trade_weapons";buy[] = {5,"ItemGoldBar10oz"};sell[] = {2,"ItemGoldBar10oz"};};
	class m240_scoped_EP1_DZE {type = "trade_weapons";buy[] = {5,"ItemGoldBar10oz"};sell[] = {2,"ItemGoldBar10oz"};};
	class Pecheneg_DZ {type = "trade_weapons";buy[] = {5,"ItemGoldBar10oz"};sell[] = {2,"ItemGoldBar10oz"};};	
	class MK17_Sniper_DZ {type = "trade_weapons";buy[] = {6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class MK17_Sniper_SD_DZ {type = "trade_weapons";buy[] = {2,"ItemGoldBar10oz"};sell[] = {1,"ItemGoldBar10oz"};};
	class M110_NV_DZ {type = "trade_weapons";buy[] = {7,"ItemGoldBar10oz"};sell[] = {4,"ItemGoldBar10oz"};};
	class RSASS_DZ {type = "trade_weapons";buy[] = {6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class RSASS_SD_DZ {type = "trade_weapons";buy[] = {-6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class HK417_Sniper_DZ {type = "trade_weapons";buy[] = {6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class HK417_Sniper_SD_DZ {type = "trade_weapons";buy[] = {-6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class MK14_Sniper_DZ {type = "trade_weapons";buy[] = {6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class MK14_Sniper_SD_DZ {type = "trade_weapons";buy[] = {-6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class DMR_DZ {type = "trade_weapons";buy[] = {6,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class DMR_Gh_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {31,"ItemGoldBar"};};	
	class M21_DZ {type = "trade_weapons";buy[] = {5,"ItemGoldBar10oz"};sell[] = {3,"ItemGoldBar10oz"};};
	class XM2010_DZ {type = "trade_weapons";buy[] = {8,"ItemGoldBar10oz"};sell[] = {4,"ItemGoldBar10oz"};};
	class XM2010_SD_DZ {type = "trade_weapons";buy[] = {-1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};	
	class BAF_LRR_scoped {type = "trade_weapons";buy[] = {-1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar10oz"};};
	class BAF_LRR_scoped_W {type = "trade_weapons";buy[] = {-1,"ItemGoldBar10oz"};sell[] = {5,"ItemGoldBar10oz"};};
	//Tan Lapua // DayZ Mod version
	class L115A3_DZ {type = "trade_weapons";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};
	//Green Lapua // DayZ Mod version
	class L115A3_2_DZ {type = "trade_weapons";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};	
	class MSR_DZ {type = "trade_weapons";buy[] = {1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};	
	class MSR_SD_DZ {type = "trade_weapons";buy[] = {-1,"ItemBriefcase100oz"};sell[] = {5,"ItemGoldBar10oz"};};	
	class m107_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {6,"ItemGoldBar10oz"};};
	class Anzio_20_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {8,"ItemGoldBar10oz"};};
	class BAF_AS50_scoped_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {8,"ItemGoldBar10oz"};};
	class KSVK_DZE {type = "trade_weapons";buy[] = {1,"ItemBriefcase100oz"};sell[] = {6,"ItemGoldBar10oz"};};
	class BAF_L85A2_RIS_TWS_DZ {type = "trade_weapons";buy[] = {-1,"ItemGoldBar"};sell[] = {8,"ItemGoldBar10oz"};};
};

//Ammunition
class Category_4 {
	class 30Rnd_556x45_StanagSD {type = "trade_items";buy[] = {4,"ItemSilverBar10oz"};sell[] = {2,"ItemSilverBar10oz"};};
	class 20Rnd_762x51_B_SCAR {type = "trade_items";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class 20Rnd_762x51_SB_SCAR {type = "trade_items";buy[] = {1,"ItemGoldBar"};sell[] = {5,"ItemSilverBar10oz"};};
	class 20Rnd_762x51_FNFAL {type = "trade_items";buy[] = {4,"ItemSilverBar10oz"};sell[] = {2,"ItemSilverBar10oz"};};
	class 20Rnd_762x51_DMR {type = "trade_items";buy[] = {8,"ItemGoldBar"};sell[] = {4,"ItemGoldBar"};};
	class 20Rnd_762x51_RSASS {type = "trade_items";buy[] = {8,"ItemGoldBar"};sell[] = {4,"ItemGoldBar"};};
	class 20Rnd_762x51_RSASS_SD {type = "trade_items";buy[] = {-8,"ItemGoldBar"};sell[] = {4,"ItemGoldBar"};};	
	class 5Rnd_762x67_XM2010 {type = "trade_items";buy[] = {6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class 5Rnd_762x67_XM2010_SD {type = "trade_items";buy[] = {-6,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};		
	class 5Rnd_86x70_L115A1 {type = "trade_items";buy[] = {6,"ItemGoldBar"};sell[] = {2,"ItemGoldBar"};};
	class 7Rnd_86x70_MSR {type = "trade_items";buy[] = {7,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class 7Rnd_86x70_MSR_SD {type = "trade_items";buy[] = {-7,"ItemGoldBar"};sell[] = {3,"ItemGoldBar"};};
	class 10Rnd_127x99_M107 {type = "trade_items";buy[] = {-1,"ItemGoldBar"};sell[] = {5,"ItemGoldBar"};};
	class 3rnd_Anzio_20x102mm {type = "trade_items";buy[] = {-1,"ItemGoldBar"};sell[] = {8,"ItemGoldBar"};};
	class 5Rnd_127x99_AS50 {type = "trade_items";buy[] = {-1,"ItemGoldBar"};sell[] = {8,"ItemGoldBar"};};
	class 5Rnd_127x99_as50_CP {type = "trade_items";buy[] = {-1,"ItemGoldBar"};sell[] = {8,"ItemGoldBar"};};
	class 5Rnd_127x108_KSVK {type = "trade_items";buy[] = {4,"ItemGoldBar"};sell[] = {2,"ItemGoldBar"};};
	class 200Rnd_556x45_M249 {type = "trade_items";buy[] = {4,"ItemGoldBar"};sell[] = {2,"ItemGoldBar"};};
	class 100Rnd_762x51_M240 {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class 100Rnd_762x54_PK {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
};

//Clothes
class Category_5 {
	class Skin_CZ_Special_Forces_GL_DES_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Drake_Light_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Soldier_Sniper_PMC_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_FR_OHara_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_FR_Rodriguez_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_CZ_Soldier_Sniper_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Graves_Light_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Soldier_Bodyguard_AA12_PMC_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Camo1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Rocket_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Sniper1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Soldier1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_Soldier_TL_PMC_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_USMC_Soldier_Officer_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_USMC_Soldier_MG_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_USMC_Soldier_Pilot_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_FR_TL_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_FR_R_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_FR_Sapper_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};	
	class Skin_FR_Marksman_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_FR_Assault_R_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_CZ_Soldier_SL_DES_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_US_Soldier_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_UN_CDF_Soldier_Guard_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_UN_CDF_Soldier_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_GER_Soldier_TL_EP1_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_BAF_Soldier_Officer_MTP_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	class Skin_BAF_Soldier_N_MTP_DZ {type = "trade_items";buy[] = {2,"ItemGoldBar"};sell[] = {1,"ItemGoldBar"};};
	
	//Bandit Skins sell only
	class Skin_Bandit1_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_Bandit2_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_BanditW1_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_BanditW2_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_GUE_Commander_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_GUE_Soldier_2_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_GUE_Soldier_CO_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_GUE_Soldier_Crew_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_GUE_Soldier_Sniper_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_Ins_Soldier_GL_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_TK_INS_Soldier_EP1_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_TK_INS_Warlord_EP1_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_RU_Soldier_Crew_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_TK_INS_Soldier_AR_EP1_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_TK_GUE_Soldier_EP1_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_RU_Soldier_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_RU_Soldier_Officer_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_RUS_Soldier1_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_RUS_Commander_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_MVD_Soldier_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_Ins_Soldier_2_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_Ins_Commander_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_Ins_Soldier_Crew_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
	class Skin_CDF_Soldier_DZ {type = "trade_items";buy[] = {-2,"ItemGoldBar"};sell[] = {7,"ItemSilverBar10oz"};};
};
