//Air Vehicles
class Category_6 {
	class pook_transport_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class pook_transport_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class pook_transport_CDF_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class pook_transport_CDF_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class pook_gunship_DZE {type = "trade_any_vehicle";buy[] = {40000,"worth"};sell[] = {10000,"worth"};};
	class pook_gunship_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class pook_gunship_CDF_DZE {type = "trade_any_vehicle";buy[] = {40000,"worth"};sell[] = {10000,"worth"};};
	class pook_gunship_CDF_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class AH6J_EP1_DZE {type = "trade_any_vehicle";buy[] = {30000,"worth"};sell[] = {10000,"worth"};};
	class AH6J_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class UH1H_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class UH1H_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class UH1H_CDF_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class UH1H_CDF_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class UH1H_WD_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class UH1H_WD_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class UH1H_2_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class UH1H_2_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class UH1H_DES_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class UH1H_DES_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class UH1H_GREY_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class UH1H_GREY_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class UH1H_BLACK_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class UH1H_BLACK_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class UH1H_SAR_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class UH1H_SAR_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class Mi17_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class Mi17_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class Mi17_TK_EP1_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class Mi17_TK_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class Mi17_UN_CDF_EP1_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class Mi17_UN_CDF_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class Mi17_CDF_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class Mi17_CDF_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class Mi17_DES_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class Mi17_DES_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class Mi17_GREEN_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class Mi17_GREEN_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class Mi17_BLUE_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class Mi17_BLUE_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class Mi17_BLACK_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class Mi17_BLACK_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class Mi171Sh_CZ_EP1_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};	
	class Mi171Sh_CZ_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class MH60S_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class MH60S_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class Ka60_GL_PMC_DZE {type = "trade_any_vehicle";buy[] = {30000,"worth"};sell[] = {10000,"worth"};};
	class Ka60_GL_PMC_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class AW159_Lynx_BAF_DZE {type = "trade_any_vehicle";buy[] = {30000,"worth"};sell[] = {10000,"worth"};};
	class AW159_Lynx_BAF_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class UH60M_EP1_DZE {type = "trade_any_vehicle";buy[] = {40000,"worth"};sell[] = {10000,"worth"};};
	class UH60M_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class UH1Y_DZE {type = "trade_any_vehicle";buy[] = {40000,"worth"};sell[] = {10000,"worth"};};
	class UH1Y_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class CH_47F_EP1_DZE {type = "trade_any_vehicle";buy[] = {50000,"worth"};sell[] = {20000,"worth"};};	
	class CH_47F_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {20000,"worth"};};	
	class CH_47F_EP1_Black_DZE {type = "trade_any_vehicle";buy[] = {50000,"worth"};sell[] = {20000,"worth"};};
	class CH_47F_EP1_Black_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {20000,"worth"};};
	class CH_47F_EP1_GREY_DZE {type = "trade_any_vehicle";buy[] = {50000,"worth"};sell[] = {20000,"worth"};};
	class CH_47F_EP1_GREY_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {20000,"worth"};};
	class CH_47F_EP1_DES_DZE {type = "trade_any_vehicle";buy[] = {50000,"worth"};sell[] = {20000,"worth"};};
	class CH_47F_EP1_DES_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {20000,"worth"};};	
};

//Ground Vehicles
class Category_7 {
	class Pickup_PK_TK_GUE_EP1_DZE {type = "trade_any_vehicle";buy[] = {800,"worth"};sell[] = {400,"worth"};};
	class Pickup_PK_TK_GUE_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {400,"worth"};};
	class Pickup_PK_GUE_DZE {type = "trade_any_vehicle";buy[] = {1000,"worth"};sell[] = {500,"worth"};};
	class Pickup_PK_GUE_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {500,"worth"};};
	class Pickup_PK_INS_DZE {type = "trade_any_vehicle";buy[] = {1000,"worth"};sell[] = {500,"worth"};};
	class Pickup_PK_INS_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {500,"worth"};};
	class Offroad_DSHKM_Gue_DZE {type = "trade_any_vehicle";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class Offroad_DSHKM_Gue_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {1000,"worth"};};
	class ArmoredSUV_PMC_DZE {type = "trade_any_vehicle";buy[] = {30000,"worth"};sell[] = {10000,"worth"};};	
	class ArmoredSUV_PMC_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class LandRover_MG_TK_EP1_DZE {type = "trade_any_vehicle";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};	
	class LandRover_MG_TK_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {3000,"worth"};};
	class LandRover_Special_CZ_EP1_DZE {type = "trade_any_vehicle";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	class LandRover_Special_CZ_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class UAZ_MG_TK_EP1_DZE {type = "trade_any_vehicle";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class UAZ_MG_TK_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {3000,"worth"};};
	class BAF_Jackal2_L2A1_D_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class BAF_Jackal2_L2A1_D_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class BAF_Jackal2_L2A1_W_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class BAF_Jackal2_L2A1_W_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class BAF_Jackal2_GMG_D_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class BAF_Jackal2_GMG_D_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class BAF_Jackal2_GMG_W_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};
	class BAF_Jackal2_GMG_W_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class BTR40_MG_TK_GUE_EP1_DZE {type = "trade_any_vehicle";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	class BTR40_MG_TK_GUE_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class BTR40_MG_TK_INS_EP1_DZE {type = "trade_any_vehicle";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	class BTR40_MG_TK_INS_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class GAZ_Vodnik_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};	
	class GAZ_Vodnik_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class BRDM2_HQ_TK_GUE_EP1_DZE {type = "trade_any_vehicle";buy[] = {20000,"worth"};sell[] = {10000,"worth"};};	
	class BRDM2_HQ_TK_GUE_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};			
	class HMMWV_Armored_DZE {type = "trade_any_vehicle";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	class HMMWV_Armored_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class HMMWV_M2_DZE {type = "trade_any_vehicle";buy[] = {30000,"worth"};sell[] = {10000,"worth"};};
	class HMMWV_M2_DZ_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};	
	class HMMWV_M998A2_SOV_DES_EP1_DZE {type = "trade_any_vehicle";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	class HMMWV_M998A2_SOV_DES_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class HMMWV_M1151_M2_CZ_DES_EP1_DZE {type = "trade_any_vehicle";buy[] = {40000,"worth"};sell[] = {10000,"worth"};};
	class HMMWV_M1151_M2_CZ_DES_EP1_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {10000,"worth"};};
	class T810A_PKT_ACR_DZE {type = "trade_any_vehicle";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	class T810A_PKT_ACR_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class T810A_PKT_DES_ACR_DZE {type = "trade_any_vehicle";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	class T810A_PKT_DES_ACR_DZ {type = "trade_any_vehicle";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
};

//Weapons
class Category_8 {
	//Holo SD desert camo
	class G36C_Camo_Holo_SD_DZ {type = "trade_weapons";buy[] = {1000,"worth"};sell[] = {500,"worth"};};
	class G36A_Camo_DZ {type = "trade_weapons";buy[] = {600,"worth"};sell[] = {300,"worth"};};
	class G36A_Camo_SD_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {700,"worth"};};
	class G36K_Camo_DZ {type = "trade_weapons";buy[] = {600,"worth"};sell[] = {300,"worth"};};
	class G36K_Camo_SD_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {700,"worth"};};
	//CCO green camo
	class M4A1_Camo_CCO_DZ {type = "trade_weapons";buy[] = {600,"worth"};sell[] = {300,"worth"};};
	class M4A1_Camo_CCO_SD_DZ {type = "trade_weapons";buy[] = {1000,"worth"};sell[] = {500,"worth"};};
	//GL Holo Green Camo
	class M4A1_Camo_Holo_GL_DZ {type = "trade_weapons";buy[] = {800,"worth"};sell[] = {400,"worth"};};
	class M4A1_Camo_Holo_GL_SD_DZ {type = "trade_weapons";buy[] = {1200,"worth"};sell[] = {600,"worth"};};	
	//Camo
	class M4A3_Camo_DZ {type = "trade_weapons";buy[] = {400,"worth"};sell[] = {200,"worth"};};		
	//ACOG Camo
	class M4A3_Camo_ACOG_DZ {type = "trade_weapons";buy[] = {800,"worth"};sell[] = {400,"worth"};};		
	//CCO FL Desert Camo
	class M4A3_DES_CCO_DZ {type = "trade_weapons";buy[] = {600,"worth"};sell[] = {300,"worth"};};
	//ACOG GL Grey
	class M4A3_ACOG_GL_DZ {type = "trade_weapons";buy[] = {1000,"worth"};sell[] = {500,"worth"};};	
	class FNFAL_ANPVS4_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {1000,"worth"};};
	// FN_FAL_ANPVS4_DZE has toggleable night vision, attachment support
	class FN_FAL_ANPVS4_DZE {type = "trade_weapons";buy[] = {3000,"worth"};sell[] = {1000,"worth"};};
	class Mk43_DZ {type = "trade_weapons";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class MK43_Holo_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {1200,"worth"};};
	class MK43_ACOG_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {1400,"worth"};};
	class M240_DZ {type = "trade_weapons";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class M240_CCO_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {1200,"worth"};};
	class M240_Holo_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {1200,"worth"};};
	class Mk48_DZ {type = "trade_weapons";buy[] = {3000,"worth"};sell[] = {1000,"worth"};};
	class Mk48_CCO_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {1200,"worth"};};
	class Mk48_Holo_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {1200,"worth"};};
	class Mk48_DES_CCO_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {1200,"worth"};};
	class M249_m145_EP1_DZE {type = "trade_weapons";buy[] = {5000,"worth"};sell[] = {2000,"worth"};};
	class MK43_M145_DZ {type = "trade_weapons";buy[] = {5000,"worth"};sell[] = {2000,"worth"};};
	class m240_scoped_EP1_DZE {type = "trade_weapons";buy[] = {5000,"worth"};sell[] = {2000,"worth"};};
	class Pecheneg_DZ {type = "trade_weapons";buy[] = {5000,"worth"};sell[] = {2000,"worth"};};	
	class WA2000_DZ {type = "trade_weapons";buy[] = {4000,"worth"};sell[] = {2000,"worth"};};	
	class MK17_Sniper_DZ {type = "trade_weapons";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class MK17_Sniper_SD_DZ {type = "trade_weapons";buy[] = {2000,"worth"};sell[] = {1000,"worth"};};
	class M110_NV_DZ {type = "trade_weapons";buy[] = {7000,"worth"};sell[] = {4000,"worth"};};
	class RSASS_DZ {type = "trade_weapons";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class RSASS_SD_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {3000,"worth"};};	
	class HK417_Sniper_DZ {type = "trade_weapons";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class HK417_Sniper_SD_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {3000,"worth"};};
	class MK14_Sniper_DZ {type = "trade_weapons";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class MK14_Sniper_SD_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {3000,"worth"};};
	class DMR_DZ {type = "trade_weapons";buy[] = {6000,"worth"};sell[] = {3000,"worth"};};
	class DMR_Gh_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {3100,"worth"};};	
	class M21_DZ {type = "trade_weapons";buy[] = {5000,"worth"};sell[] = {3000,"worth"};};
	class XM2010_DZ {type = "trade_weapons";buy[] = {8000,"worth"};sell[] = {4000,"worth"};};
	class XM2010_SD_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class BAF_LRR_scoped {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class BAF_LRR_scoped_W {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	//Tan Lapua // DayZ Mod version
	class L115A3_DZ {type = "trade_weapons";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	//Green Lapua // DayZ Mod version
	class L115A3_2_DZ {type = "trade_weapons";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};
	class MSR_DZ {type = "trade_weapons";buy[] = {10000,"worth"};sell[] = {5000,"worth"};};	
	class MSR_SD_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class Barrett_MRAD_Iron_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {5000,"worth"};};
	class Barrett_MRAD_CCO_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {5200,"worth"};};
	class Barrett_MRAD_Sniper_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class m107_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {6000,"worth"};};
	class Anzio_20_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {8000,"worth"};};
	class BAF_AS50_scoped_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {8000,"worth"};};
	class M200_CheyTac_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {8000,"worth"};};
	class KSVK_DZE {type = "trade_weapons";buy[] = {10000,"worth"};sell[] = {6000,"worth"};};
	class BAF_L85A2_RIS_TWS_DZ {type = "trade_weapons";buy[] = {-1,"worth"};sell[] = {8000,"worth"};};
};

//Ammunition
class Category_9 {	
	class 30Rnd_556x45_StanagSD {type = "trade_items";buy[] = {40,"worth"};sell[] = {20,"worth"};};
	class 6Rnd_762x51_WA2000 {type = "trade_items";buy[] = {100,"worth"};sell[] = {50,"worth"};};
	class 20Rnd_762x51_B_SCAR {type = "trade_items";buy[] = {600,"worth"};sell[] = {300,"worth"};};
	class 20Rnd_762x51_SB_SCAR {type = "trade_items";buy[] = {100,"worth"};sell[] = {50,"worth"};};
	class 20Rnd_762x51_FNFAL {type = "trade_items";buy[] = {40,"worth"};sell[] = {20,"worth"};};
	class 20Rnd_762x51_DMR {type = "trade_items";buy[] = {800,"worth"};sell[] = {400,"worth"};};
	class 20Rnd_762x51_RSASS {type = "trade_items";buy[] = {800,"worth"};sell[] = {400,"worth"};};
	class 20Rnd_762x51_RSASS_SD {type = "trade_items";buy[] = {-1,"worth"};sell[] = {400,"worth"};};	
	class 5Rnd_762x67_XM2010 {type = "trade_items";buy[] = {600,"worth"};sell[] = {300,"worth"};};
	class 5Rnd_762x67_XM2010_SD {type = "trade_items";buy[] = {-1,"worth"};sell[] = {300,"worth"};};		
	class 5Rnd_86x70_L115A1 {type = "trade_items";buy[] = {600,"worth"};sell[] = {200,"worth"};};
	class 7Rnd_86x70_MSR {type = "trade_items";buy[] = {700,"worth"};sell[] = {300,"worth"};};
	class 7Rnd_86x70_MSR_SD {type = "trade_items";buy[] = {-1,"worth"};sell[] = {300,"worth"};};
	class 10Rnd_86x70_MRAD {type = "trade_items";buy[] = {-1,"worth"};sell[] = {400,"worth"};};	
	class 10Rnd_127x99_M107 {type = "trade_items";buy[] = {-1,"worth"};sell[] = {500,"worth"};};
	class 3rnd_Anzio_20x102mm {type = "trade_items";buy[] = {-1,"worth"};sell[] = {800,"worth"};};
	class 5Rnd_127x99_AS50 {type = "trade_items";buy[] = {-1,"worth"};sell[] = {800,"worth"};};
	class 5Rnd_127x99_as50_CP {type = "trade_items";buy[] = {-1,"worth"};sell[] = {800,"worth"};};
	class 5Rnd_127x108_KSVK {type = "trade_items";buy[] = {400,"worth"};sell[] = {200,"worth"};};
	class 5Rnd_408_CheyTac {type = "trade_items";buy[] = {-1,"worth"};sell[] = {800,"worth"};};
	class 200Rnd_556x45_M249 {type = "trade_items";buy[] = {400,"worth"};sell[] = {200,"worth"};};
	class 100Rnd_762x51_M240 {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class 100Rnd_762x54_PK {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
};

//Clothes
class Category_10 {
	class Skin_Bandit1_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_Bandit2_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_BanditW1_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_BanditW2_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_GUE_Commander_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_GUE_Soldier_2_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_GUE_Soldier_CO_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_GUE_Soldier_Crew_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_GUE_Soldier_Sniper_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_Ins_Soldier_GL_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_TK_INS_Soldier_EP1_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_TK_INS_Warlord_EP1_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_RU_Soldier_Crew_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_TK_INS_Soldier_AR_EP1_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_TK_GUE_Soldier_EP1_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_RU_Soldier_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_RU_Soldier_Officer_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_RUS_Soldier1_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_RUS_Commander_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_MVD_Soldier_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_Ins_Soldier_2_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_Ins_Commander_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_Ins_Soldier_Crew_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};
	class Skin_CDF_Soldier_DZ {type = "trade_items";buy[] = {200,"worth"};sell[] = {100,"worth"};};	
	
	//Hero Skins sell only
	class Skin_CZ_Special_Forces_GL_DES_EP1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_Drake_Light_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_Soldier_Sniper_PMC_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_FR_OHara_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_FR_Rodriguez_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_CZ_Soldier_Sniper_EP1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_Graves_Light_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_Soldier_Bodyguard_AA12_PMC_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_Camo1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_Rocket_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_Sniper1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_Soldier1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_Soldier_TL_PMC_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_USMC_Soldier_Officer_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_USMC_Soldier_MG_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_USMC_Soldier_Pilot_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_FR_TL_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_FR_R_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_FR_Sapper_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};	
	class Skin_FR_Marksman_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_FR_Assault_R_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_CZ_Soldier_SL_DES_EP1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_US_Soldier_EP1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_UN_CDF_Soldier_Guard_EP1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_UN_CDF_Soldier_EP1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_GER_Soldier_TL_EP1_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_BAF_Soldier_Officer_MTP_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
	class Skin_BAF_Soldier_N_MTP_DZ {type = "trade_items";buy[] = {-1,"worth"};sell[] = {70,"worth"};};
};
