class 29Rnd_30mm_AGS30 : CA_Magazine { 
	scope = 2; 
	displayName = "HE Rounds"; 
	model = "\z\addons\dayz_epoch\models\30mm_mag.p3d";
	picture = "\z\addons\dayz_epoch\pictures\equip_30mm_mag_ca.paa";
	ammo = "G_30mm_HE"; 
	count = 29; 
	type = "256";
	initSpeed = 185; 
	maxLeadSpeed = 100; 
	nameSound = "grenadelauncher"; 
	weight = 16;
};
class 48Rnd_40mm_MK19 : CA_Magazine { 
	scope = 2; 
	displayName = "Mk. 19 40mm"; 
	model = "\z\addons\dayz_epoch\models\40mm_mag.p3d";
	picture = "\z\addons\dayz_epoch\pictures\equip_40mm_mag_ca.paa";
	ammo = "G_40mm_HE"; 
	count = 48; 
	type = "256";
	initSpeed = 240; 
	maxLeadSpeed = 100; 
	nameSound = "grenadelauncher"; 
	weight = 25;
};
class 2000Rnd_762x51_M134 : CA_Magazine { 
	count = 2000; 
	scope = 2; 
	displayName = "M134 7.62 Nato"; 
	picture = "\z\addons\dayz_epoch\pictures\equip_m134_mag_ca.paa";
	model = "\z\addons\dayz_epoch\models\m134_mag.p3d";
	ammo = "B_762x51_3RndBurst"; 
	type = "256";
	maxLeadSpeed = 200; 
	tracersEvery = 5; 
	nameSound = "mgun";
	weight = 50;
};
class 100Rnd_127x99_M2 : CA_Magazine { 
	scope = 2; 
	displayName = "M2 Machine Gun"; 
	model = "\z\addons\dayz_epoch\models\50cal_mag.p3d";
	picture = "\z\addons\dayz_epoch\pictures\equip_50cal_mag_ca.paa";
	ammo = "B_127x99_Ball"; 
	count = 100; 
	type = "256";
	initSpeed = 930; 
	maxLeadSpeed = 200; 
	tracersEvery = 3; 
	lastRoundsTracer = 5; 
	nameSound = "mgun"; 
	weight = 8;
};
class 50Rnd_127x107_DSHKM : CA_Magazine { 
	scope = 2; 
	displayName = "DShKM"; 
	picture = "\z\addons\dayz_epoch\pictures\equip_Dshkm_mag_ca.paa";
	model = "\z\addons\dayz_epoch\models\dshkm_mag.p3d";
	ammo = "B_127x107_Ball"; 
	count = 50; 
	type = "256";
	initSpeed = 850; 
	maxLeadSpeed = 200; 
	tracersEvery = 3; 
	lastRoundsTracer = 5; 
	nameSound = "mgun"; 
	weight = 4;
};