class CfgTraderCategory {
	#include "Category\Hero.hpp"
	#include "Category\Bandit.hpp"
	#include "Category\BlackMarket.hpp"
	#include "Category\Weapons.hpp"
	#include "Category\Ammunition.hpp"
	#include "Category\GeneralStore.hpp"
	#include "Category\MedicalSupplies.hpp"
	#include "Category\Parts.hpp"
	#include "Category\Vehicles.hpp"
	#include "Category\AirVehicles.hpp"
	#include "Category\Boats.hpp"
	#include "Category\Wholesale.hpp"
	#include "Category\Currency.hpp"
};