class CfgGlasses {
	class None;
	class Pro_Helmet : None {};
	class Pro_Helmet_g : None {};
	class Pro_Helmet_2 : None {};
	class Kevlar_Helmet : None {};
	class Kevlar_Helmet_g : None {};
	class wdl_helmet : None {};
	class Barett : None {};
	class US_green_beret : None {};
	class US_black_beret : None {};
	class Barett_g : None {};
	class Bdu_cap : None {};
	class Bdu_cap_g : None {};
	class b_TacticalGlasses : None {};
	class headset : None {};
	class headset_g : None {};
	class gasmask : None {};
	class gasmask2 : None {};
	class gasmask_helmet : None {};
	class gasmask_red : None {};
	class gasmask_helmet2 : None {};
	class pilot_mask : None {};
	class pilot_mask_v : None {};
	class pilot_v : None {};
	class skull_cap : None {};
	class skull_cap2 : None {};
	class taliban_hat_shadow : None {};
	class dive_mask : None {};
	class BlackSun_sof_w : None {};
	class RedSun_sof_w : None {};
	class None_sof_w : None {};
	class goggles_winter : None {};
};