//Disables automatic group chat spam "CEASE FIRE", "READY", "REGROUP", "UNKNOWN 12'OCLOCK", etc. but breaks some AI behavior (like driving land vehicles)
/*class RadioProtocolEmpty {
	class Words {};
	class Arguments {};
	class Default {priority = -1; timeout = -1;};
	class Report {priority = -1; timeout = -1;};
	class PriorityReport {priority = -1; timeout = -1;};
	class Confirmation {priority = -1; timeout = -1;};
	class Completition {priority = -1; timeout = -1;};
	class JoinCompleted {priority = -1; timeout = -1;};
	class Failure {priority = -1; timeout = -1;};
	class Notify {priority = -1; timeout = -1;};
	class Detected {priority = -1; timeout = -1;};
	class NormalCommand {priority = -1; timeout = -1;};
	class CriticalReport {priority = -1; timeout = -1;};
	class UrgentCommand {priority = -1; timeout = -1;};
	class UICommand	{priority = -1; timeout = -1;};
	class Design {priority = -1; timeout = -1;};
	class ClausePosition {};
	class ClausePositionNear {};
	class SentUnitKilled {};
	class SentSupportAskHeal {};
	class SentSupportAskRepair {};
	class SentSupportAskRefuel {};
	class SentSupportAskRearm {};
	class SentSupportConfirm {};
	class SentSupportReady {};
	class SentSupportDone {};
	class SentSupportNotAvailable {};
	class SentHealthCritical {};
	class SentDammageCritical {};
	class SentFuelCritical {};
	class SentFuelLow {};
	class SentAmmoCritical {};
	class SentAmmoLow {};
	class SentReportPosition {};
	class SentIsLeader {};
	class SentCommandCompleted {};
	class SentJoinCompleted {};
	class SentFireReady {};
	class SentFireNegative {};
	class SentCommandFailed {};
	class SentDestinationUnreacheable {};
	class SelectEnemyDetectedSentence {};
	class SentEnemyDetectedGroupCoreRelative {};
	class SentEnemyDetectedOnGridReference {};
	class SentEnemyDetectedLocationRelative {};
	class SentEnemyDetectedUnitRelative {};
	class SentEnemyDetectedSenderRelative {};
	class SentObjectDestroyed {};
	class SentObjectDestroyedUnknown {};
	class SentContact {};
	class SentUnderFire {};
	class SentCoverMe {};
	class SentCovering {};
	class SentSuppressing {};
	class SentReloading {};
	class SentThrowingGrenade {};
	class SentThrowingSmoke {};
	class SentIncomingGrenade {};
	class SentEnemyContact {};
	class SentEndangered {};
	class SentRouted {};
	class SentWitnessDeadBody {};
	class SentWitnessKilled {};
	class SentCombatGeneric {};
	class SentCheering {};
	class SentScreaming {};
	class SentClear {};
	class SentRepeatCommand {};
	class SentWhereAreYou {};
	class SentReturnToFormation {};
	class SentFormColumn {};
	class SentFormStaggeredColumn {};
	class SentFormWedge {};
	class SentFormEcholonLeft {};
	class SentFormEcholonRight {};
	class SentFormVee {};
	class SentFormLine {};
	class SentFormFile {};
	class SentFormDiamond {};
	class SentBehaviourCareless {};
	class SentBehaviourSafe {};
	class SentBehaviourAware {};
	class SentBehaviourCombat {};
	class SentBehaviourStealth {};
	class SentOpenFire {};
	class SentOpenFireInCombat {};
	class SentHoldFire {};
	class SentHoldFireInCombat {};
	class SentCeaseFireInsideGroup {};
	class SentCeaseFire {};
	class SentLooseFormation {};
	class SentKeepFormation {};
	class SentUnitPosDown {};
	class SentUnitPosMiddle {};
	class SentUnitPosUp {};
	class SentUnitPosAuto {};
	class SentFormPosAdvance {};
	class SentFormPosStayBack {};
	class SentFormPosFlankLeft {};
	class SentFormPosFlankRight {};
	class SentReportStatus {};
	class SentTeam {};
	class SentTeamPlural {};
	class SentWatchTgt {};
	class SentWatchDir {};
	class SentWatchPos {};
	class SentWatchAround {};
	class SentNoTarget {};
	class SentTarget {};
	class SentEngage {};
	class SentFire {};
	class SentEngageNoTarget {};
	class SentFireNoTarget {};
	class SelectCmdMoveSentence {};
	class SentCmdMoveGroupRelative {};
	class SentCmdMoveRecipientsRelative {};
	class SentCmdMoveToGrid {};
	class SentCmdMoveToTarget {};
	class SentCmdMoveToObject {};
	class SentCmdMoveLocationRelative {};
	class SentCmdHealSomeone {};
	class SentCmdHealSelf {};
	class SentAssemble {};
	class SentDisassemble {};  
	class SentCmdActionTakeBag {};
	class SentCmdActionDropBag {};
	class SentCmdActionOpenBag {};
	class SentLightsOn {};  
	class SentLightsOff {};
	class SentPointersOn {};
	class SentPointersOff {};
	class SentCmdHeal {};
	class SentCmdHealFar {};
	class SentCmdHealAt {};
	class SentCmdRepair {};
	class SentCmdRepairFar {};
	class SentCmdRepairAt {};
	class SentCmdRefuel {};
	class SentCmdRefuelFar {};
	class SentCmdRefuelAt {};
	class SentCmdRearm {};
	class SentCmdRearmFar {};
	class SentCmdRearmAt {};
	class SentCmdSupport {};
	class SentCmdSupportFar {};
	class SentCmdSupportAt {};
	class SentCmdDropWeapon {};
	class SentCmdDropMagazine {};
	class SentCmdTakeWeapon {};
	class SentCmdTakeWeaponFar {};
	class SentCmdTakeWeaponAt {};
	class SentCmdTakeMagazine {};
	class SentCmdTakeMagazineFar {};
	class SentCmdTakeMagazineAt {};
	class SentCmdAction {};
	class SentCmdActionNear {};
	class SentCmdActionFar {};
	class SentCmdActionAt {};
	class SentCmdTakeFlag {};
	class SentCmdTakeFlagFar {};
	class SentCmdTakeFlagAt {};
	class SentCmdReturnFlag {};
	class SentCmdReturnFlagFar {};
	class SentCmdReturnFlagAt {};
	class SentCmdEject {};
	class SentCmdPlaceCharge {};
	class SentCmdDetonate {};
	class SentCmdActivateTimer {};
	class SentCmdDeactivateBomb {};
	class SentCmdDeactivateMine {};
	class SentCmdTakeMine {};
	class SentCmdLightFire {};
	class SentCmdLightFireFar {};
	class SentCmdLightFireAt {};
	class SentCmdPutOutFire {};
	class SentCmdPutOutFireFar {};
	class SentCmdPutOutFireAt {};
	class SentCmdOpenDoor {};
	class SentCmdOpenDoorFar {};
	class SentCmdOpenDoorAt {};
	class SentCmdCloseDoor {};
	class SentCmdCloseDoorFar {};
	class SentCmdCloseDoorAt {};
	class SentCmdFollowMe {};
	class SentCmdFollow {};
	class SentCmdAttack {};
	class SentAttackNoTarget {};
	class SentCmdFire {};
	class SentCmdGetIn {};
	class SentCmdGetInCommander {};
	class SentCmdGetInDriver {};
	class SentCmdGetInPilot {};
	class SentCmdGetInGunner {};
	class SentCmdGetInCargo {};
	class SentCmdSwitchToDriver {};
	class SentCmdSwitchToGunner {};
	class SentCmdSwitchToCommander {};
	class SentCmdSwitchToCargo {};
	class SentCmdGetOut {};
	class SentCmdStop {};
	class SentCmdExpect {};
	class SentCmdHide {};
	class SentCmdDismiss {};
	class SentNotifyAttack {};
	class SentNotifyAttackSubgroup {};
	class SentNotifySupport {};
	class SentConfirmMove {};
	class SentConfirmAttack {};
	class SentConfirmOther {};
	class SentARTYFireAt {};
	class SentRepairThat {};
	class SentARTYRoundsComplete {};
	class SentARTYCannotExecuteAdjustCoordinates {};
	class SentARTYCannotExecuteThatsOutsideOurFiringEnvelope {};
	class SelectVehicleMoveSentence {};
	class VehicleMoveGroupRelative {};
	class VehicleMoveRecipientsRelative {};
	class VehicleMoveToGrid {};
	class VehicleMoveToObject {};
	class VehicleMoveLocationRelative {};
	class VehicleWatchTgt {};
	class VehicleWatchPos {};
	class VehicleJoin {};
	class VehicleFire {};
	class VehicleTarget {};
	class VehicleNoTarget {};
	class VehicleCeaseFire {};
	class VehicleForward {};
	class VehicleStop {};
	class VehicleBackward {};
	class VehicleFaster {};
	class VehicleSlower {};
	class VehicleLeft {};
	class VehicleRight {};
	class VehicleManualFire {};
	class VehicleCancelManualFire {};
	class VehicleDirectFire {};
	class VehicleLoad {};
	class VehicleLoadMagazine {};
	class VehicleAzimut {};
	class VehicleFireFailed {};
};
class RadioProtocolBase: RadioProtocolEmpty {};
class RadioProtocol_EP1_EN: RadioProtocolEmpty {};
class RadioProtocol_EP1_TK: RadioProtocolEmpty {};
class RadioProtocol_WMN_EP1_TK: RadioProtocolEmpty {};
class RadioProtocolEN: RadioProtocolEmpty {};
class RadioProtocolRU: RadioProtocolEmpty {};
class RadioProtocolCZ: RadioProtocolEmpty {};
class RadioProtocol_BAF: RadioProtocolEmpty {};
*/