Industrial[] =
{
	//Tools
	{Loot_WEAPON,		3,		ItemKnife},
	{Loot_WEAPON,		6,		ItemToolbox},
	{Loot_WEAPON,		2,		ItemFlashlight},
//	{Loot_WEAPON,		8,		ItemCrowbar},
	{Loot_VEHICLE,		8,		WeaponHolder_ItemCrowbar},
//	{Loot_WEAPON,		5,		ItemHatchet},
	{Loot_VEHICLE,		5,		WeaponHolder_ItemHatchet},
	{Loot_WEAPON,		1,		ItemPickaxe},
	{Loot_WEAPON,		2,		ItemPickaxeBroken},
	{Loot_WEAPON,		1,		ItemSledgeHammer},
	{Loot_WEAPON,		2,		ItemSledgeHammerBroken},
	
	//Items
	{Loot_MAGAZINE,		6,		ItemSandbag},
	{Loot_MAGAZINE,		4,		ItemJerryCan},
	{Loot_MAGAZINE,		1,		ItemWire},
	{Loot_MAGAZINE,		4,		ItemTankTrap},
	{Loot_MAGAZINE,		1,		equip_brick},
	{Loot_MAGAZINE,		3,		equip_duct_tape},
	{Loot_MAGAZINE,		2,		equip_hose},
	{Loot_MAGAZINE,		6,		equip_nails},
//	{Loot_MAGAZINE,		3,		ItemScrews},
	{Loot_MAGAZINE,		1,		equip_scrapelectronics},
	{Loot_MAGAZINE,		2,		equip_metal_sheet},
	{Loot_MAGAZINE,		2,		equip_1inch_metal_pipe},
	{Loot_MAGAZINE,		2,		equip_2inch_metal_pipe},
	{Loot_MAGAZINE,		12,		ItemPlank},
	
	//Other
	{Loot_GROUP,		15,		Parts},
	{Loot_PILE,			10,		Trash, 1, 3},
	{Loot_PILE,			4,		Consumable, 1, 2},
	{Loot_GROUP,		8,		Generic}
};

/*	OLD
{Loot_WEAPON,		3,		ItemKnife},
{Loot_WEAPON,		2,		ItemToolbox},
{Loot_WEAPON,		6,		ItemFlashlight},
{Loot_WEAPON,		8,		ItemCrowbar},
{Loot_WEAPON,		5,		ItemHatchet},
{Loot_WEAPON,		1,		Mosin_Nagant},
{Loot_WEAPON,		3,		Mosin_Nagant_broken},
{Loot_WEAPON,		1,		ItemPickaxe},
{Loot_WEAPON,		2,		ItemPickaxeBroken},
{Loot_WEAPON,		1,		ItemSledgeHammer},
{Loot_WEAPON,		2,		ItemSledgeHammerBroken},

{Loot_MAGAZINE,		6,		ItemSandbag},
{Loot_MAGAZINE,		3,		equip_rope},
{Loot_MAGAZINE,		1,		ItemWire},
{Loot_MAGAZINE,		4,		ItemTankTrap},
{Loot_MAGAZINE,		1,		ItemSodaSmasht},
{Loot_MAGAZINE,		1,		ItemSodaDrwaste},
{Loot_MAGAZINE,		1,		FoodCanPowell},
{Loot_MAGAZINE,		1,		FoodChipsSulahoops},
{Loot_MAGAZINE,		1,		equip_brick},
{Loot_MAGAZINE,		3,		equip_duct_tape},
{Loot_MAGAZINE,		2,		equip_hose},
{Loot_MAGAZINE,		6,		equip_nails},
{Loot_MAGAZINE,		1,		equip_rag},
{Loot_MAGAZINE,		1,		equip_lever},
{Loot_MAGAZINE,		1,		equip_scrapelectronics},
{Loot_MAGAZINE,		2,		equip_metal_sheet},
{Loot_MAGAZINE,		2,		equip_2inch_metal_pipe},
{Loot_MAGAZINE,		2,		equip_1inch_metal_pipe},
{Loot_MAGAZINE,		16,		ItemPlank},

{Loot_MAGAZINE,		4,		PartGeneric},
{Loot_MAGAZINE,		5,		PartWheel},
{Loot_MAGAZINE,		2,		PartFueltank},
{Loot_MAGAZINE,		2,		PartEngine},
{Loot_MAGAZINE,		4,		PartGlass},
{Loot_MAGAZINE,		4,		ItemJerrycan},
{Loot_MAGAZINE,		3,		ItemFuelcan},

{Loot_GROUP,		10,		Trash},
{Loot_GROUP,		5,		ammo},
{Loot_GROUP,		8,		generic},
{Loot_GROUP,		3,		attachmentsGeneric},
*/