class USEC_ch53_E;
class CH53_DZE : USEC_ch53_E {
	displayname = "USEC CH53E DZE";
	displaynameshort = "CH53_DZE";
	enablemanualfire = 0;
	scope = 2;
	side = 2;
	crew = "";
	typicalCargo[] = {};
	hiddenSelections[] = {};
	radartype = 0;
	class TransportMagazines{};
	class TransportWeapons{};
	commanderCanSee = 2+16+32;
	gunnerCanSee = 2+16+32;
	driverCanSee = 2+16+32;
	transportMaxWeapons = 25;
	transportMaxMagazines = 80;
	transportmaxbackpacks = 15;
};